<!DOCTYPE html>
<html>
  <head>
    <title>Cancellation is a serendipitous success</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="./fonts.css"/>
    <link rel="stylesheet" href="./mermaid.forest.css">
    <style>
        @page {
            size: 1210px 681px;
            margin: 0;
        }

        @media print {
            .remark-slide-scaler {
                width: 100% !important;
                height: 100% !important;
                transform: scale(1) !important;
                top: 0 !important;
                left: 0 !important;
            }
        }

        body { font-family: 'Droid Serif'; }
        h1, h2, h3 {
            font-family: 'Yanone Kaffeesatz';
            font-weight: normal;
        }
        .remark-code, .remark-inline-code { font-family: 'Droid Sans Mono'; }
        .remark-inline-code {
          color:#585260;
        }
        .remark-slide-content {
            padding-bottom: 4em;
        }
        div.footer {
            position: absolute;
            bottom: 12px;
            width: 100%;
            opacity: .6;
        }
        .footer .flexcontainer {
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            margin-right: 190px;
        }

        .border {
            border: 2px solid steelblue;
        }

        div.emscripten-output {
            font-family: 'Droid Sans Mono';
            font-size: 14pt;
            border: 2px solid steelblue;
            padding: 5px;
            background: black;
            color: lightgreen;
        }

        img {
            width: 80%;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            padding: 5px;
            border: 1px solid steelblue;
        }
        th {
            border-bottom: 3px solid steelblue;
            color: black;
        }
        pre {
            margin: 0.2em 0px 0.2em
        }
        
        .accent {
            color: seagreen
        }
        .hidden {
            visibility: hidden
        }

        .scale-p5 {
          transform: scale(0.5);
          transform-origin: top left;
        }
        .scale-p75 {
          transform: scale(0.75);
          transform-origin: top left;
        }
        .scale-p8 {
          transform: scale(0.8);
          transform-origin: top left;
        }
        .scale-p9 {
          transform: scale(0.9);
          transform-origin: top left;
        }

        .image-10 img {width: 10%}
        .image-20 img {width: 20%}
        .image-30 img {width: 30%}
        .image-40 img {width: 40%}
        .image-50 img {width: 50%}
        .image-60 img {width: 60%}
        .image-70 img {width: 70%}
        .image-80 img {width: 80%}

        .column:first-of-type {float:left}
        .column:last-of-type {float:right}

        .split-30 .column:first-of-type {width: 30%}
        .split-30 .column:last-of-type {width: 69%}
        .split-30:after {
          clear: both;
          content: '';
          display: block;
        }
        .split-40 .column:first-of-type {width: 40%}
        .split-40 .column:last-of-type {width: 59%}
        .split-40:after {
          clear: both;
          content: '';
          display: block;
        }
        .split-50 .column:first-of-type {width: 50%}
        .split-50 .column:last-of-type {width: 49%}
        .split-50:after {
          clear: both;
          content: '';
          display: block;
        }
        .split-60 .column:first-of-type {width: 60%}
        .split-60 .column:last-of-type {width: 39%}
        .split-60:after {
          clear: both;
          content: '';
          display: block;
        }
        .split-70 .column:first-of-type {width: 70%}
        .split-70 .column:last-of-type {width: 29%}
        .split-70:after {
          clear: both;
          content: '';
          display: block;
        }

        .column ul:first-of-type {
            margin: .2em
        }


        blockquote {
            background: lightgray ;
            border-left: 10px solid deepskyblue;
            margin: 1.5em 0px;
            padding: 0.5em 10px;
            quotes: "\201C""\201D""\2018""\2019";
        }
        blockquote:before {
            color: #ccc;
            font-size: 4em;
            line-height: 0.1em;
            margin-right: 0.25em;
            vertical-align: -0.4em;
        }
        blockquote p {
            display: inline;
        }

        .mermaid p {
            display: inline;
        }
        .mermaid svg {
          display: inline;
          margin: auto;
          max-height: 480px
        }
    </style>
  </head>
  <body>
    <textarea hidden=true id="source">

layout: true
<div class="footer"><div class="flexcontainer"><span>.body[[[http://wg21.link/p1677r2](http://wg21.link/p1677r2)]]</span><span>.center[]</span><span>.body[&copy; 2019 Kirk Shoop ([github](http://github.com/kirkshoop) [twitter](http://twitter.com/kirkshoop))]</span></div></div>

---

class: middle

.center[

# P1677R2 - Cancellation is serendipitous success

.accent[
### Was: Cancellation is not an Error
]

]

???

> * 

---

class: middle

.center[

## Why is it hard to stop a running frame?

.accent[
### (requesting cancellation is solved, use `stop_source`/`stop_token`)
]

]

???

> * 

---

## papers

- [P0660R4](http://wg21.link/P0660R4) is an earlier revision of the `jthread` paper that defined a `std::interrupted` exception and a
`std::this_thread::throw_if_interrupted()` API. These were intended to exit an arbitrary scope using
the exception mechanism.

- [P0876R5](http://wg21.link/P0876R5) is an earlier revision of the `fiber_context` paper that defined a `std::unwind_exception` exception that would be thrown from `~fiber_context` if the fiber was suspended. These were intended to exit an arbitrary scope in the suspended fiber using
the exception mechanism.

- [P1662R0 - Async RAII](http://wg21.link/P1662R0) is a Cologne paper that describes how to exit an arbitrary scope in a suspended coroutine __without__ using the exception mechanism

- [P0443R11 - Executors](http://wg21.link/P0443R11) is a Belfast paper that describes how to exit an active Sender __without__ using the exception mechanism

***

--

- These papers are trying to express the same mechanism in different domains

- `jthread` removed `std::interrupted` based on discussion in an SG1 meeting in Seattle ([wiki](http://wiki.edg.com/bin/view/ExecSeattle2018/MinutesDay2)) 

- `fiber_context` removed `std::unwind_exception` after discussion in Kona and a subsequent platform-specific exception mechanism after discussion in Cologne

???

> * 

---

## Issues discussed for the exception mechanism approaches

- noexcept functions .accent[cannot] be on the stack when `std::interrupted` is thrown

- all functions that cross ABI boundaries, such as callbacks passed to C functions, like OS APIs, </br> .accent[must
suppress] the `std::interrupted` exception

- all `catch(...)` .accent[must rethrow], when the exception is `std::interrupted`

- all `catch(...)` .accent[must be called] for `std::interrupted`, since many `catch(...)` are used to cleanup and restore invariants
and some of those instances are in std lib implementations.

- all `catch(const std::interrupted&)` .accent[must rethrow].

It is interesting to note that the ABI boundary restriction .accent[conflicts with] the catch restrictions.

???

> * 

---

class: middle

.center[

## Why is stopping a running frame a success condition?

.accent[
### 
]

]

???

> * 

---

### Dual of the Strategy pattern

.split-50[
.column[
### Cancellation
#### An effort is cancelled when some .accent[higher-level] goal .accent[has already been satisfied], rendering the current effort unnecessary, and possibly wasteful.
]
.column[
### Exception
#### In the strategy pattern, we abort a strategy when we discover that a .accent[low-level] goal .accent[cannot be satisfied], rendering the current strategy impossible.
]
]
???

> * 
---

### Dual of the Strategy pattern

Both patterns share the idea of early exit from an operation, and the thinking that has gone into the early exit
model for exceptions also applies to cancellation. In particular:

- There are discrete points in the code where early exit may be initiated, i.e., throw statements or cancellation
points.

- Early exit, whether by exception or cancellation, must unwind the stack, executing destructors.

- Some functions must guarantee to their callers that they will not exit early.

On the other hand, some things are reversed:

- The reason for an exception is governed at a low level, near the throw point. The reason for cancellation is
governed at a high level, near the cancellable effort.

- High-level code must be prepared to accept failure for a wide variety of low level reasons. Low-level code
must be prepared to be cancelled for a wide variety of high-level reasons.

- When a sub-strategy of a larger strategy fails, we only abort the sub-strategy. When a larger effort
encompassing a sub-effort is rendered unnecessary, we abort the larger effort.
???

> * 

---

### concurrency

When there is no concurrency, then the result of a function call can be used to skip additional work and return
early.

```cpp
void sequential() {
  process_left();
  if (stop_requested()) { return; }
  process_right();
}
```

When there is concurrency, then the result of an async function must also be able to skip related concurrent work
and return early.

```cpp
void concurrent() {
  sync_wait(
    when_all(
      process_left(), 
      process_right()));
}
```

???

> * 

---

### sequence consumption

When there is a generator, then the result of a function call can be used to skip additional work and return
early.

```cpp
void sequential(auto values) {
  for(auto&& value : values) {
    process_left(value);
    if (stop_requested()) { break; }
    process_right(value);
  }
}
```

When there is an async_generator, then the result of an async function must also be able to skip related concurrent work
and return early.

```cpp
void concurrent(auto values) {
  sync_wait(
    values |
    transform([](auto&& value) {
      return when_all(process_left(value), process_right(value));
    }) | merge());
}
```

???

> * 

---

### sequence generation

When there is a generator, then the result of a function call can be used to skip additional work and return
early.

```cpp
generator<int> values() {
    for (;;) {
      co_yield next()); // return int
      if (stop_requested()) { break; }
    }
    co_return; // return void
}
```

When there is an async_generator, then the result of an async function must also be able to skip related concurrent work
and return early.

```cpp
async_generator<int> values() {
  for (;;) {
    co_yield co_await next()); // return int
    if (stop_requested()) { break; }
  }
  co_return; // return void
}
```

???

> * 

---

### options for unwind

channel | example | notes
--------|---------|------
value-piggyback | `return optional<T>;` | .accent[generally avoided] <br/>because it clutters the success path
error-piggyback | `throw cancellation_error();` | .accent[staunchly defended] <br/>because it does not clutter the success path </br> .accent[bad effects] because an exception does not </br> make a good success signal </br> would you use throw to exit a for loop instead of `break`?
break | `[](){ `<br/>&nbsp;&nbsp;`for(;;) { `<br/>&nbsp;&nbsp;&nbsp;&nbsp;`f(); `<br/>&nbsp;&nbsp;&nbsp;&nbsp;`if (is_done()) {break; } `<br/>&nbsp;&nbsp;`} `<br/>`}` | `break` exits the for-loop with with something <br/>similar to serendipitous-success, but .accent[there is no feature] <br/>to break out of a function with serendipitous-success

???

> * 

---

### Conclusions

- #### it should be considered an artifact of history that unwind is considered exceptional

- #### a language mechanism for expressing successful-unwind independently from exceptional-unwind is needed

  - #### a statement to initiate successful-unwind (`return break;`/`break return;`/`throw goto`)

  - #### a means of using successful-unwind for control flow is needed (`scope_unwind`/`catch goto`)

  - #### a means of creating a barrier to successful-unwind (`nounwind`/overload `noexcept`)

???

> * 

---

class: middle

.center[

## Questions?

.accent[
### 
]

]

???

> * 

---

class: middle

.center[

## Functions

.accent[
### 
]

]

???

> * 

---

## Function signals

In C, there are three ways to communicate the result of a function:

channel | example 
--|--
return a value | `int i = f();` 
set value(s) into out-parameter(s) | `int i=0; f(i);`
call a parameter, that is a function, with arguments(s) | `f([](int i){..});`
~~set a global~~ | NOPE

***
--

C++ added a third mechanism for communicating a result - throwing exceptions.

- allowed code to focus on the .accent[path of success]
- delegated the responsibility for exception handling to the .accent[caller by default]
- support for signalling exceptions is .accent[implicitly added] to every function (noexcept uses the exception signal to terminate)
- `catch(...)` is used to .accent[restore invariants] during exception unwind
- error logic can be extracted into pages that are only loaded when an exception is thrown (.accent[cold-path]) to optimize for the success case

???

> * 

---

class: middle

.center[

## Tasks

.accent[
### 
]

]

???

> * 

---

## Contrast with Functions

- A Task is .accent[invoked from a stack frame] that may not exist when result|exception is emitted

--

- The only remaining .accent[fragment of the stack frame] that invoked the Task is the callback or continuation provided to the Task

--

- The signals result|exception that would be delivered to the stack frame that invoked a Function .accent[must be delivered] to the callback or continuation of a Task
***
???

> * 

---

class: middle

.center[

## Cancellation

.accent[
### 
]

]

???

> * 

---

## Cancellation Signals

### .accent[Cancellation-Request] 

Consumer -> Producer

mechanism | notes
----------|------
`stop_source`/`stop_token` | from [P0660R9](http://wg21.link/P0660R9) 

--

.accent[ 
# Solved!
]

???

> * 

---

## Cancellation Signals

### .accent[serendipitous-success]

Consumer &lt;- Producer

channel | example | notes
--------|---------|------
value-piggyback | `return optional<T>;` | .accent[generally avoided] <br/>because it clutters the success path
error-piggyback | `throw cancellation_error();` | .accent[staunchly defended] <br/>because it does not clutter the success path
break | `[](){ `<br/>&nbsp;&nbsp;`for(;;) { `<br/>&nbsp;&nbsp;&nbsp;&nbsp;`f(); `<br/>&nbsp;&nbsp;&nbsp;&nbsp;`if (is_done()) {break; } `<br/>&nbsp;&nbsp;`} `<br/>`}` | `break` exits the for-loop with with something <br/>similar to serendipitous-success, but .accent[there is no feature] <br/>to break out of a function with serendipitous-success

???

> * 

---

## Cancellation Signals

.accent[Not all cancellation is async]

```cpp
template<class T>
struct generator {
  T next() {..}
};
```

.split-50[

.column[

```cpp
generator<int> fortyTwos() {
  for (int i = 0; i < 5; ++i) {
    // the g.next()
    // resumes with the int 42
    co_yield 42;
  }
  // the g.next()
  // resumes with?
  co_return;
}
```
]
.column[
```cpp
// assumes that g.next()
// completes with 
// serendipitous-success
void foo() {
  auto g = fortyTwos();
  for(;;) {
    auto fortyTwo = g.next();
  }
}
```
]
]

???

> * 

---
## Cancellation Signals

.split-50[

.column[

#### Real
***
```cpp
std::optional<int> op() {
  if (!has_feature()) {
    return std::nullopt;
  }
  return feature();
}

void foo() {
  // ..
  auto i = op();
  if (!i) { return; }
  // use *i..
} // jumps here when the feature is
  // not supported
```
]
.column[

#### Imaginary
***
```cpp
int op() {
  if (!has_feature()) {
    `break return`;
  }
  return feature();
}

void foo() {
  // ..
  auto i = op();
  //
  // use i..
} // jumps here when the feature is
  // not supported  
```

]
]

???

> * 

---

class: middle

.center[

## Algorithms

.accent[
### 
]

]

???

> * 

---

## Discover concepts by studying Data Structures and .accent[Algorithms]
 
"It might be surprising to you, but I find the subject of iterators extremely hard to teach. 
The main reason is that I find the notion self-evident and all the fundamental design decision non-negotiable. 
But I also know that somehow even those people who are very enthusiastic about iterators, the STL “specialists,” often demonstrate that their understanding of iterator fundamentals is quite shaky. 
.accent[The fact that I find the concept so self-evident is the result of many years of trying alternatives and finding that they do not work. 
In some sense the only way for someone to fully understand why they have to be the way they are is by trying hundreds of different algorithms and finding the abstraction that allows the most beautiful and efficient representation of them.] 
As a matter of fact, the only way of finding a useful abstraction is by trying to write code in terms of it. 
Sadly enough, people tend to define abstractions faster than they try them. 
There is even a pernicious idea of having “architects,” which are often people who produce abstractions without writing code. 
It is a worthwhile thing to remember that the most successful abstraction ever introduced in computer science – an abstraction of a file as a sequence of bytes with the help of which Ken Thompson revolutionized systems design – did not originate as an abstraction at all, but as a specific data structure for implementing files. 
.accent[Good abstractions come from efficient algorithms and data structures and not from “architectural” considerations]."

.accent[Stepanov, A.], 2006, _Notes On Programming_, _Lecture 13. Iterators_ ([pdf](http://www.cs.rpi.edu/~musser/gsd/notes-on-programming-2006-10-13.pdf))

???

> * 

---


## Discover concepts by studying Data Structures and .accent[Algorithms]

.split-50[
.column[
".accent[In some sense the only way for someone to fully understand why they have to be the way they are is by trying hundreds of different algorithms and finding the abstraction that allows the most beautiful and efficient representation of them.]"

".accent[Good abstractions come from efficient algorithms and data structures and not from “architectural” considerations]."

.accent[Stepanov, A.], 2006, _Notes On Programming_, _Lecture 13. Iterators_ ([pdf](http://www.cs.rpi.edu/~musser/gsd/notes-on-programming-2006-10-13.pdf))
]
.column[
]
]

???

> * 

---

## Algorithms that cancel

- the `when_any()` (aka `amb()`) algorithm which cancels the other producers once one of them produced a
result (and emits no error).

- the `when_all()` (aka `zip()`) algorithm which cancels the other producers when one completes with an
error.

- the `take_until()` algorithm which cancels a source when a trigger completes and cancels a trigger
when the source completes.

- the `timeout()` algorithm which cancels a source when it does not produce a value before the timeout
and then emits `timeout_error` (which is defined as part of the `timeout()` algorithm).

???

> * 

---

## Algorithms that cancel

.split-50[

.column[

```cpp
auto f(auto source) {
  return take_until(
    source.async_bar(servers.current()), 
    after(10s));
}
```

]

.column[
`f` returns a task that uses the result of `async_bar` if it arrives within 10 seconds. Otherwise, there is no result and no error.

- `after` produces a timer that completes after 10 seconds
- `take_until` takes two arguments, source and trigger, and the first one to complete .accent[signals a cancellation-request] to the other
- `take_until` never propagates an error or value from the trigger
- `take_until` .accent[signals a serendipitous-success] when the trigger wins
- `take_until` propagates the source (value|error|serendipitous-success) when the source wins.
]
]

???

> *

---

## Algorithms that cancel

signal | `take_until` | `when_any`
-------|--------------|-----------
value | propagated from .accent[source], not trigger | propagated from .accent[first] to complete
error | propagated from .accent[source], not trigger | propagated from .accent[first] to complete
serendipitous-success | propagated from .accent[source] and .accent[trigger] | propagated from .accent[first] to complete

--

- These algorithms intentionally signalled cancellation-request and .accent[expect the result] to be serendipitous-success.

--

- These algorithms consider the expected serendipitous-success to be on the .accent[success-path]

--

- Users debugging code using these algorithms with a break-point on error .accent[never want to stop] for these expected signals on the success-path
***
???

> * 

---

## Algorithms for errors

.split-50[

.column[

```cpp
auto f(auto source) {
  return retry_when(
    filter_error(
      source.async_bar(servers.current()), 
      [](E e){
        return e == server_unavailable;
      }), 
    [](E){ return after(1s); });
}
```

]

.column[
`f` returns a task that will retry a task every second until it completes with value|error == server_unavailable|serendipitous-success.

- `filter_error` takes two arguments, a source and a predicate
- `filter_error` calls the predicate when an error occurs 
- `filter_error` completes with serendipitous-success when the predicate returns true
- `filter_error` otherwise propagates the source signal unchanged
]
]

???

> * 

---

## Algorithms for errors

.split-50[

.column[

```cpp
auto f(auto source) {
  return retry_when(
    filter_error(
      source.async_bar(servers.current()), 
      [](E e){
        return e == server_unavailable;
      }), 
    [](E){ return after(1s); });
}
```

]

.column[
`f` returns a task that will retry a task every second until it completes with value|error == server_unavailable|serendipitous-success.

- `retry_when` takes two arguments, a source and a selector
- `retry_when` calls the selector when an error occurs and starts the task the selector returns
- `retry_when` starts the source when the value signal is received from the task returned from the selector
- `retry_when` otherwise propagates the error|serendipitous-success signals from the task returned from the selector
]
]

???

> * 

---

## Algorithms for errors

.split-50[

.column[

```cpp
auto f(auto source) {
  return retry(
    source.async_bar(servers.current()), 
    3);
}
```

]

.column[
`f` returns a task that will retry a task 3 times until it completes with value|serendipitous-success.

- `retry` takes two arguments, a source and a count
- `retry` starts the source when the error signal is received from the source and the count is > 0
- `retry` otherwise propagates the value|error|serendipitous-success signals from the source
]
]

???

> * 

---

## Algorithms for errors

signal | `filter_error` | `retry_when` | `retry`
-------|----------------|--------------|--------
value | propagated from .accent[source] | propagated from .accent[source] | propagated from .accent[source]
error | .accent[source] when predicate returns false | delegated to the task returned from .accent[selector] | starts source .accent[count] times and otherwise propagates the error
serendipitous-success | propagated from .accent[source] | propagated from .accent[source] and from the task returned from .accent[selector] | propagated from .accent[source]

--

- `filter_error` needs to omit errors that match the predicate and needs to complete without a value and without an error in that case

--

- `retry_when` and `retry` must only retry on errors, they must not retry on value|serendipitous-success
***
???

> * 

---

## Algorithms for errors - using exception signal

signal | `filter_error` | `retry_when` | `retry`
-------|----------------|--------------|--------
value | propagated from .accent[source] | propagated from .accent[source] | propagated from .accent[source]
error | .accent[source] when predicate returns false | delegated to the task returned from .accent[selector] | starts source .accent[count] times and otherwise propagates the error
serendipitous-success | propagated from .accent[source] | propagated from .accent[source] and from the task returned from .accent[selector] | propagated from .accent[source]

- `filter_error` would otherwise define a filtered_error exception and emit filtered_error when the predicate was true

- `retry_when` would then, either have a list of all the exceptions that will ever mean do-not-retry (cancellation_error, filtered_error, ..), or users will have to manually list all the errors, in each selector written

- `retry` would then, either have a list of all the exceptions that will ever mean do-not-retry (cancellation_error, filtered_error, ..), or will have to take a new predicate where users will have to manually list all the errors that should not retry

???

> * 

---

## Algorithms for errors - using exception signal

.split-50[

.column[

```cpp
auto f(auto source) {
    return retry_when(
      filter_error(
        source.async_bar(servers.current()), 
        [](E e){
          return e == server_unavailable;
        }), 
      [](E e){
          `if (do_not_retry(e)) return error(e);`
          return after(1s); });
  }
```

This looks simple but is an example of how every algorithm that uses (rather than forwards) the error channel needs to incorporate the cross-cutting concern that separate algorithms like `filter_error` and `transform_error` should be dedicated to.

]
.column[
```cpp
auto f(auto source) {
  return retry(
    source.async_bar(servers.current()), 
    3, 
    `do_not_retry`);
}
```
]
]

???

> * 

---

class: middle

.center[

## Task Representations

.accent[
### 
]

]

???

> * 

---

## Task Representations

- [P0660R4](http://wg21.link/P0660R4) is an earlier revision of the `jthread` paper that defined a `std::interrupted` exception and a
`std::this_thread::throw_if_interrupted()` API. These were intended to exit an arbitrary scope using
the exception mechanism.

- [P0876R5](http://wg21.link/P0876R5) is an earlier revision of the `fiber_context` paper that defined a `std::unwind_exception` exception that would be thrown from `~fiber_context` if the fiber was suspended. These were intended to exit an arbitrary scope in the suspended fiber using
the exception mechanism.

- [P1662R0](http://wg21.link/P1662R0) is a Cologne paper that describes how to exit an arbitrary scope in a suspended coroutine __without__ using the exception mechanism

- [P1660R0](http://wg21.link/P1660R0) is a Cologne paper that describes how to exit an active Sender __without__ using the exception mechanism

***

--

- These are trying to express the same mechanism in different domains

- `jthread` removed `std::interrupted` based on discussion in an SG1 meeting in Seattle ([wiki](http://wiki.edg.com/bin/view/ExecSeattle2018/MinutesDay2)) 

- `fiber_context` removed `std::unwind_exception` after discussion in Kona and a subsequent platform-specific exception mechanism after discussion in Cologne

???

> * 

---

## Issues discussed for the exception mechanism approaches

- noexcept functions .accent[cannot] be on the stack when `std::interrupted` is thrown

- all functions that cross ABI boundaries, such as callbacks passed to C functions, like OS APIs, .accent[must
suppress] the `std::interrupted` exception

- all `catch(...)` .accent[must rethrow], when the exception is `std::interrupted`

- all `catch(...)` .accent[must be called] for `std::interrupted`, since many `catch(...)` are used to cleanup and restore invariants
and some of those instances are in std lib implementations.

- all `catch(const std::interrupted&)` .accent[must rethrow].

It is interesting to note that the ABI boundary restriction .accent[conflicts with] the catch restrictions.

???

> * 

---

## Conclusion

- Many different domains require a facility to signal that there will be no value or error result from a function or task.

- Libraries adding callbacks should have support for serendipitous-success. The only paper in Cologne that defines a callback that supports this is [P1660R0](http://wg21.link/P1660R0). This would be a valid callback according to the definition in [P1660R0](http://wg21.link/P1660R0)

```cpp
struct my_callback {
    void operator()(my_foo, my_bar);
    void operator()(my_foo);

    void error(my_error_code);
    void error(std::exception_ptr); 
      // does not require exception support - 
      // just an empty type will do

    void done(); 
      // operator() and error have not 
      // and will not be called
};
```

???

> * 

---

## Language

The paper also contains imaginary language features that might represent serendipitous-success in domains like `jthread` and `fiber_context`

???

> * 

---

class: middle

.center[

## Questions?

.accent[
### 
]

]

???

> * 
    </textarea>
    <!-- <script src="https://gnab.github.io/remark/downloads/remark-latest.min.js" type="text/javascript" >
    </script> -->
    <script src="./remark-latest.min.js" type="text/javascript" >
    </script>
    <script src="./CustomElements.min.js" type="text/javascript" >
    </script>
    <script src="./element.js" type="text/javascript" >
    </script>
    <script src="./mermaid.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML&delayStartupUntil=configured" type="text/javascript" >
    </script>
    <script>

        var slideshow = remark.create({
            ratio: "16:9",
            highlightLanguage: "cpp",
            highlightStyle: "atelier-cave-light",
            highlightLines: true,
            highlightSpans: true
        });

        MathJax.Hub.Config({
            displayAlign: "center",
            tex2jax: {
                skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
                inlineMath: [['$','$'], ['\\(','\\)']]
            }
        });
        MathJax.Hub.Configured();

        mermaid.initialize({
          mermaid: {
            startOnLoad: false,
            cloneCssStyles: false
          }
        });

        function initMermaid(slide) {
          try {
            mermaid.init(undefined, '.remark-visible .mermaid p');
          } catch(e) {
            console.log(e);
          }
        }
        initMermaid(slideshow.getSlides()[slideshow.getCurrentSlideIndex()]);

        slideshow.on("afterShowSlide", function(slide) {
            initMermaid(slide);
        });
        slideshow.on("print", function(slide) {
            initMermaid(slide);
        });
    </script>
      </body>
</html>
